name = "gandonl"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-07-14"
compatibility_flags = ["nodejs_als"]

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "gandonl"
database_id = "25ace723-df73-4814-8e24-952b1a571315"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "NEWS_MEDIA"
bucket_name = "gandonl-news"

[vars]
DISCORD_REDIRECT_URI = "https://gand.onl/auth/discord/callback"
